modLoader = "javafml"
loaderVersion = "[1,)"
license = "BSD-3-Clause License"
issueTrackerURL = "https://github.com/RealYusufIsmail-Mc-Mods/RealYusufIsmail-Core-Neo/issues"
#logoFile="examplemod.png"
credits = "realyusufismail"
authors = "RealYusufIsmail-Mc-Mods org"
[[mods]]
modId = "realyusufismailcore"
version = "1.20.2-1.0.3"
displayName = "RealYusufIsmail Core"
updateJSONURL = "https://forge.curseupdate.com/497372/realyusufismail-core"
logoFile = "logo.png"
description = '''
Shared library for Yusuf Arfan Ismail's mods
 '''

[[dependencies.realyusufismailcore]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.realyusufismailcore]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2, 1.21)"
ordering = "NONE"
side = "BOTH"
